name: Shards live ISO
id: shards.liveiso
includespath: includes.liveiso

stages:
- id: build
  base: docker.io/library/archlinux:latest
  singlelayer: false
  labels:
    maintainer: hello
  modules:
    - name: init
      type: shell
      commands:
        - pacman -Syu --noconfirm
        - pacman-key --init
        - pacman-key --populate archlinux
        - mkdir -p /sysroot

    - name: install-image
      type: shell
      commands:
        - if ! [ -e /sources/install-image/images ]; then exit 1; fi
        - mkdir -p /usr/share/shardsimages
        - cp /sources/install-image/images/* /usr/share/shardsimages/
        - xz -T$(nproc) /usr/share/shardsimages/*.img
      sources:
        - type: local
          url: images

    - name: build-depends
      type: pacman
      packages:
        - "linux"
        - "systemd"
        - "cryptsetup"
        - "btrfs-progs"
        - "glibc-locales"
        - "tree"
        - "dracut"
        - "gnome"
        - "gdm"
        - "udisks2"
        - "meson"
        - "base-devel"
        - "gnome-backgrounds"
        - "gnome-console"
        - "gnome-control-center"
        - "gnome-disk-utility"
        - "gnome-menus"
        - "gnome-session"
        - "gnome-settings-daemon"
        - "gnome-shell"
        - "gnome-text-editor"
        - "orca"
        - "xdg-desktop-portal-gnome"
        - "xdg-user-dirs-gtk"
        - "gdm"
        - "pv"
        - "plymouth"

    - name: initramfs
      type: shell
      commands:
        - mkdir -p /efi
        - KVERSION=$(ls -1 /usr/lib/modules | head -n1)
        - cp /usr/lib/modules/${KVERSION}/vmlinuz /efi/vmlinuz-linux
        - dracut --no-machineid --kernel-image /efi/vmlinuz-linux --kver "$(ls -1 /usr/lib/modules | head -n1)" --kernel-cmdline 'rw quiet splash root=live:LABEL=shards-liveiso' --add dmsquash-live --install plymouth --install head --install tail --install less --install lsof /efi/initramfs.img
        - SYSTEMD_ESP_PATH=/efi bootctl install --no-variables

    - name: services
      type: shell
      commands:
        - useradd -m lain
        - usermod -aG wheel lain
        - echo 'lain:lain' | chpasswd
        - systemctl enable gdm.service
        - cp /sources/services/gdm-config/custom.conf /etc/gdm/custom.conf
      sources:
        - type: local
          url: files/gdm-config

    - name: shards-installer
      type: meson
      BuildFlags:
        - "--prefix /usr"
      source:
        type: git
        url: https://github.com/Project-Shards/shards-installer.git
        branch: main

    - name: cleanup
      type: shell
      commands:
        - pacman -R --noconfirm base-devel meson
        - rm -rf /var/cache/pacman

finalize:
  - name: genimage stage1
    type: genimage
    config: "$PROJROOT/genimg/stage1.conf"
    rootpath: "$FSROOT"
    inputpath: "$PROJROOT/genimg/build"
    outputpath: "$PROJROOT/genimg/stage2"
  - name: genimage stage2
    type: genimage
    config: "$PROJROOT/genimg/stage2.conf"
    rootpath: "$PROJROOT/genimg/stage2"
    inputpath: "$PROJROOT/genimg/build"
    outputpath: "$PROJROOT/genimg/build"
