name: Shards sysupdate Images
id: shards.sysupdate
includespath: includes.sysupdate

stages:
- id: build
  base: docker.io/library/archlinux:latest
  singlelayer: false
  labels:
    maintainer: hello
  modules:
    - name: init
      type: shell
      commands:
        - pacman -Syu --noconfirm
        - mkdir -p /sysroot

    - name: build-depends
      type: pacman
      packages:
        - "linux"
        - "systemd"
        - "systemd-ukify"
        - "python-pyelftools"
        - "base-devel"
        - "cryptsetup"
        - "btrfs-progs"
        - "cpio"
        - "util-linux-libs"
        - "erofs-utils"
        - "jq"
        - "glibc-locales"
        - "tree"
        - "help2man"
        - "perl-file-slurp"
        - "sbsigntools"
        - "git"
        - "gnu-efi-libs"
        - "efivar"

    - name: modules
      type: includes
      includes:
        - modules/bootstrap-sysroot.yml
        - modules/os-release.yml
        - modules/prepare-sysroot.yml
        - modules/generate-initramfs.yml
        - modules/usr-images.yml
        - modules/update-images.yml
        - modules/kernel-image.yml

    - name: update-repo
      type: shell
      commands:
        - cd /cleanup/update-images
        - sha256sum *.xz | tee SHA256SUMS

finalize:
  - name: checkout-files
    type: shell-final
    commands:
      - mkdir -p $PROJROOT/update-images
      - cp -r $FSROOT/cleanup/usrimage/disk.raw $PROJROOT/disk-repart.raw
      - touch $PROJROOT/update-images/SHA256SUMS
      - ls $FSROOT/cleanup/
      - ls $FSROOT/cleanup/update-images
      - cat $FSROOT/cleanup/update-images/SHA256SUMS >> $PROJROOT/update-images/SHA256SUMS
      - rm $FSROOT/cleanup/update-images/SHA256SUMS
      - cp -r $FSROOT/cleanup/update-images/*.xz $PROJROOT/update-images/.
  - name: repart
    type: systemd-repart
    output: disk-repart.raw
    size: "auto"
    json: "pretty"
    spec_output: "test"
    split: false
    root: "$FSROOT/sysroot"
    empty: "refuse"
    seed: "d2006edc-a112-4e3d-9502-c04ded047acd"
