name: arch
id: arch

stages:
- id: build
  base: docker.io/library/archlinux:latest
  singlelayer: false
  labels:
    maintainer: hello
  modules:
    - name: init
      type: shell
      commands:
        - pacman -Syu --noconfirm
        - mkdir -p /sysroot
    - name: waow
      type: pacman
      packages:
        - "linux"
        - "systemd"
        - "systemd-ukify"
        - "python-pyelftools"
        - "base-devel"
        - "cryptsetup"
        - "btrfs-progs"
        - "cpio"
        - "util-linux-libs"
        - "squashfs-tools"
        - "jq"
        - "glibc-locales"
        - "tree"

    - name: setup-pacman
      type: shell
      commands:
        - cp -r /sysroot/usr /usr
        - mkdir -p /sysroot/etc/
        - cp -r /etc/pacman* /sysroot/etc/
        - mkdir -p /sysroot/var/cache/pacman
        - mkdir -p /sysroot/var/lib/pacman
        - pacman -Sy --sysroot=/sysroot

    - name: bootstrap
      type: pacman
      ExtraFlags:
        - "--sysroot=/sysroot"
      packages:
        - "base"
        - "systemd"
        - "linux"
        - "linux-firmware"
        - "neofetch"
        - "cryptsetup"
        - "btrfs-progs"
        - "plymouth"
        - "util-linux-libs"
        - "squashfs-tools"
        - "jq"
        - "glibc-locales"
        - "gnome"
        - "gdm"
        - "networkmanager"
        - "avahi"

    - name: modules
      type: includes
      includes:
        - modules/prepare-sysroot.yml
        - modules/generate-initramfs.yml

    - name: usr-image
      type: shell
      commands:
        - mkdir -p /sysroot/usr/share/factory
        - rm -rf /sysroot/usr/share/factory/etc
        - mv -T /sysroot/etc /sysroot/usr/share/factory/etc
        - mkdir -p /cleanup/usrimage
        - cp -r /sysroot/usr/lib/repart.d /cleanup/usrimage/definitions
        - rm /cleanup/usrimage/definitions/50-root.conf
        - mkdir -p /var/tmp
        - systemd-repart --defer-partitions=esp --definitions=/cleanup/usrimage/definitions --empty=create --size=auto --dry-run=no --offline=true --no-pager --seed="35e34b2b-1fcf-4ab1-ae63-bcda061741c1" --root=/sysroot --split=true /cleanup/usrimage/disk.raw --json=pretty > /cleanup/usrimage/repart.json
        - echo "done"
        - echo "root" | passwd root --stdin

    - name: ukify
      type: shell
      commands:
        - VERSION=$(ls -1 /sysroot/lib/modules | head -n1)
        - ROOTHASH=$(jq -r '(.[] | select(.type | match("^usr-.*-verity$"))).roothash' /cleanup/usrimage/repart.json)
        - echo usrhash=${ROOTHASH} >> /etc/kernel/cmdline
        - mkdir -p /efi/EFI/Linux
        - cp -r /sysroot/usr/lib/tmpfiles.d/20-systemd-stub.conf /usr/lib/tmpfiles.d/20-systemd-stub.conf
        - cp -r /sysroot/usr/lib/repart.d /usr/lib/repart.d
        - generate-initramfs /initramfs-root "${VERSION}" "/usr/lib" "/usr/lib/systemd"
        - cp -r /initramfs-root/sysroot/usr/* /initramfs-root/usr/
        - mkdir -p /initramfs-root/usr/lib/modules/"${VERSION}"/kernel/drivers/video
        - depmod -a -b /initramfs-root/usr "${VERSION}"
        - cd /initramfs-root
        - find . -print0 | sort -z | cpio --reproducible --null -H newc -o --quiet | xz --check=crc32 --lzma2=dict=1MiB -T0 >/initramfs.img
        - ukify build --linux=/boot/vmlinuz-linux --initrd=/initramfs.img --cmdline=@/etc/kernel/cmdline --output=/efi/EFI/Linux/linux.efi
        - SYSTEMD_ESP_PATH=/efi bootctl install --no-variables

finalize:
  - name: initramfs-checks
    type: shell-final
    commands:
      - mkdir -p $PROJROOT/dbg
      - cp -r $FSROOT/initramfs-root $PROJROOT/dbg/initramfs-root
      - cp -r $FSROOT/initramfs.img $PROJROOT/dbg/initramfs.img
      - cp -r $FSROOT/efi/EFI/Linux/linux.efi $PROJROOT/dbg/linux.efi
      - cp -r $FSROOT/cleanup/usrimage $PROJROOT/dbg/usrimage
      - cp -r $PROJROOT/dbg/usrimage/disk.raw $PROJROOT/disk-repart.raw
  - name: repart
    type: systemd-repart
    output: disk-repart.raw
    size: "auto"
    json: "pretty"
    spec_output: "test"
    split: false
    root: "$FSROOT/sysroot"
    empty: "refuse"
    seed: "35e34b2b-1fcf-4ab1-ae63-bcda061741c1"
