#!/usr/bin/env bash

modulename=$(cat $1 | jq -r '.name')
sourcedir=$(cat $2 | jq -r '.SourcesPath')
projroot=$(cat $2 | jq -r '.ParentPath')
pkgfile=$(cat $1 | jq -r '.pkgfile' | sed "s|%PROJROOT%|${projroot}|g")

while mapfile -t -n 10 ary && ((${#ary[@]})); do
      mkdir -p ${sourcedir}/${modulename}
      cd ${sourcedir}/${modulename}
      curl -s --parallel -OOOOOOOOOO ${ary[@]}
done < ${pkgfile}

cd /sources/${modulename}
repo-add ./bootstrap.db.tar.zst ./.*pkg*

echo "cd /sources/${modulename} && pacman -cp *.pkg* /usr/ pacman -U *.pkg* --sysroot=/sysroot --noconfirm"
